name: Commit a version change
on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  commit-version-change:
    if: ${{ github.repository == 'alextheman231/eslint-plugin' }}
    uses: alextheman231/github-actions/.github/workflows/commit-version-change.yml@21565f6ebbec63a0ce3bcda15bb77b75f1c5ad1f # v8.3.2
    with:
      create-feature-docs: true
      run-build: true
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
