name: Create feature docs
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    if: ${{ github.repository == 'alextheman231/eslint-plugin' }}
    uses: alextheman231/github-actions/.github/workflows/create-feature-docs.yml@21565f6ebbec63a0ce3bcda15bb77b75f1c5ad1f # v8.3.2
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
